#!/usr/bin/env sh

# excelviewer build and start script

DIR=`dirname $0`
$( 
    cd ${DIR} \
    && ./gradlew jar jar_swing jar_samples \
    && java -cp './build/libs/*' com.dua3.meja.excelviewer.SwingExcelViewer testdata/test.xlsx
)
