[release]
schemaVersion = 1
releaseType = "major"
bomVersion = "12.0.0"
sourceRevision = "0c14e6dde3dd178910e5d8ddc690abc2ea39ce87"

[modules.meja-core]
version = "12.0.0"
sourceRevision = "0c14e6dde3dd178910e5d8ddc690abc2ea39ce87"
selected = true
reason = "major release"

[modules.meja-db]
version = "12.0.0"
sourceRevision = "0c14e6dde3dd178910e5d8ddc690abc2ea39ce87"
selected = true
reason = "major release"

[modules.meja-fx]
version = "12.0.0"
sourceRevision = "0c14e6dde3dd178910e5d8ddc690abc2ea39ce87"
selected = true
reason = "major release"

[modules.meja-generic]
version = "12.0.0"
sourceRevision = "0c14e6dde3dd178910e5d8ddc690abc2ea39ce87"
selected = true
reason = "major release"

[modules.meja-poi]
version = "12.0.0"
sourceRevision = "0c14e6dde3dd178910e5d8ddc690abc2ea39ce87"
selected = true
reason = "major release"

[modules.meja-swing]
version = "12.0.0"
sourceRevision = "0c14e6dde3dd178910e5d8ddc690abc2ea39ce87"
selected = true
reason = "major release"

[modules.meja-ui]
version = "12.0.0"
sourceRevision = "0c14e6dde3dd178910e5d8ddc690abc2ea39ce87"
selected = true
reason = "major release"
