[versions]
projectVersion = "12.1.1-SNAPSHOT"
jdkVersion = "21"
jdkprovider-plugin = "0.11.0"
test-logger-plugin = "4.0.0"
spotbugs-plugin = "6.5.11"
cabe-plugin = "4.5.0"
sonar-plugin = "7.4.0.8496"
jmh-plugin = "0.7.3"
jreleaser-plugin = "1.26.0"

dua3-utility = "24.5.0"

ikonli = "12.4.0"
jspecify = "1.0.1"
junit-bom = "6.1.3"
log4j-bom = "2.26.1"
poi = "5.5.1"
slb4j = "0.14.1"
commons-compress = "1.26.2"

[libraries]
dua3-utility-bom = { group = "com.dua3.utility", name = "utility-bom", version.ref = "dua3-utility" }
dua3-utility = { group = "com.dua3.utility", name = "utility" }
dua3-utility-db = { group = "com.dua3.utility", name = "utility-db" }
dua3-utility-fx-icons = { group = "com.dua3.utility", name = "utility-fx-icons" }
dua3-utility-fx-icons-ikonli = { group = "com.dua3.utility", name = "utility-fx-icons-ikonli" }
dua3-utility-swing = { group = "com.dua3.utility", name = "utility-swing" }
dua3-utility-fx = { group = "com.dua3.utility", name = "utility-fx" }
dua3-utility-fx-controls = { group = "com.dua3.utility", name = "utility-fx-controls" }
ikonli-bom = { group = "org.kordamp.ikonli", name = "ikonli-bom", version.ref = "ikonli" }
ikonli-fontawesome = { group = "org.kordamp.ikonli", name = "ikonli-fontawesome-pack" }
ikonli-feather = { group = "org.kordamp.ikonli", name = "ikonli-feather-pack" }
ikonli-javafx = { group = "org.kordamp.ikonli", name = "ikonli-javafx" }
jspecify = { group = "org.jspecify", name = "jspecify", version.ref = "jspecify" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit-bom" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
log4j-bom = { group = "org.apache.logging.log4j", name = "log4j-bom", version.ref = "log4j-bom" }
log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api" }
slb4j-bom = { group = "org.slb4j", name = "slb4j-bom", version.ref = "slb4j" }
slb4j = { group = "org.slb4j", name = "slb4j" }
slb4j-ext = { group = "org.slb4j", name = "slb4j-ext" }
slb4j-ext-fx = { group = "org.slb4j", name = "slb4j-ext-fx" }
slb4j-ext-swing = { group = "org.slb4j", name = "slb4j-ext-swing" }
poi = { group = "org.apache.poi", name = "poi", version.ref = "poi" }
poi-ooxml = { group = "org.apache.poi", name = "poi-ooxml", version.ref = "poi" }
commons-compress = { group = "org.apache.commons", name = "commons-compress", version.ref = "commons-compress" }

[plugins]
jdk = { id = "com.dua3.gradle.jdkprovider", version.ref = "jdkprovider-plugin" }
test-logger = { id = "com.adarshr.test-logger", version.ref = "test-logger-plugin" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs-plugin" }
cabe = { id = "com.dua3.cabe", version.ref = "cabe-plugin" }
sonar = { id = "org.sonarqube", version.ref = "sonar-plugin" }
jmh = { id = "me.champeau.jmh", version.ref = "jmh-plugin" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser-plugin" }
